### PR TITLE
Adding labels for Xbox and PS4-DS controllers

### PR DESCRIPTION
**Pull request by ShishirPatil**
Changing button labels from just numbers, to corresponding names.

### CODE REVIEW

**Comment by ChocolateLoverRaj** [comment]
It would be nice to detect xbox / ps4 based on gamepad name. Like maybe using the name or product id from 
Gamepad name: `Xbox Wireless Controller (STANDARD GAMEPAD Vendor: 045e Product: 0b20)`

**Comment by ChocolateLoverRaj** [comment]
Also Idk if this bug is specific to my xbox controller (`Xbox Wireless Controller (STANDARD GAMEPAD Vendor: 045e Product: 0b20`) but the buttons in my controller do not match up with the buttons the page shows. I think your code doesn't include the plus pad.

Here is how mine looks like (same buttons, but different model probably):
[](https://commons.wikimedia.org/wiki/File:Microsoft-Xbox-One-controller.jpg#/media/File:Microsoft-Xbox-One-controller.jpg)  
By <a href="//commons.wikimedia.org/wiki/User:Evan-Amos" title="User:Evan-Amos">Evan-Amos</a> - <a href="//commons.wikimedia.org/wiki/File:Microsoft-Xbox-One-Console-Set-wKinect.jpg" title="File:Microsoft-Xbox-One-Console-Set-wKinect.jpg">File:Microsoft-Xbox-One-Console-Set-wKinect.jpg</a>, Public Domain, [Link](https://commons.wikimedia.org/w/index.php?curid=78906027)

**Comment by ChocolateLoverRaj** [comment]
Also wouldn't a dropdown be easier control instead of a toggle button and header (especially if you added more controllers).

**Comment by luser** [comment]
I created this repo to use as a very basic demonstration of the Gamepad API's capabilities, so I'm not planning to merge pull requests that add new features like the ones proposed here. If there are features missing from the Gamepad API itself, those are best discussed [on the W3C gamepad spec repository](https://github.com/w3c/gamepad/). Implementation issues in specific browsers should be filed as bugs with the browser vendor in question.

If you would like a more full-featured demo site, you are free to fork this repository or use the code in it in any manner you would like. I intentionally chose the least-restrictive license possible (CC0) with that in mind.

**Comment by ShishirPatil** [comment]
@ChocolateLoverRaj Thanks for the comments. The PR is closed, but I just wanted to complete the conversation - 
a) I did dabble with detecting PS4/Xbox controllers depending on name, but the issue is with so many in the market just identify themselves with random names. So, this was to catch those as well. 
b) Sure, if you want to raise a PR to my repo - I'd be more than happy to accept it.

**Pull request closed without merging**
